(VN-3) Create forgot password functionality
Vardan9898/tpuq-project pull request #13
Opened 2022-03-14 12:45 UTC by Vardan9898

closes #3

2022-03-14 14:29 UTC, vladsar approved these changes

2022-03-23 13:45 UTC, armen9494 commented
You don't need to publish `views/vendor/mail` files if you aren't going to change anything in that.

2022-03-23 13:56 UTC, armen9494 requested changes

2022-03-23 13:56 UTC, armen9494 commented on resources/views/emails/reset-password-link.blade.php
> +<a href="{{ action([\App\Http\Controllers\SessionsController::class, 'create']) }}">tpuq.test</a>
**NEVER** write in the code fixed website name. Use the config instead.
Always remember that your project later can be renamed to `vaspur` and you will need to modify ONLY env file.

2022-03-24 08:10 UTC, merged