(VN-1) Create tpuq
Vardan9898/tpuq-project pull request #2
Opened 2022-03-04 11:24 UTC by Vardan9898

closes #1

2022-03-04 13:08 UTC, vladsar requested changes

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +            'name'            => 'required',
Add type/size validation

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +            'address'         => 'required',
Add type/size validation

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +            'description'     => 'required',
Add type/size validation

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +            'mortgage_status' => 'boolean',
Is it always required or sometimes? Mention that

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +            'price'           => 'required|numeric',
Add size validation

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +        if (request()->get('mortgage_status') == null) {
This whole if else block is useless and pointless.

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +        return redirect('/properties');
Better to use actions in redirect. What if I change URL in routes? Then I'll have to go over the whole code and rename in all the places. Instead use action('...').

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +            'name'            => 'required',
Same as I mentioned above in create method

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +        if ($attributes['image'] ?? false) {
Honestly, this looks weird to me. Although it should work.
Instead you can check if `request()->has('image')`.

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +        return redirect('/properties')->with('success', 'Property Updated!');
Again, use action().

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/PropertiesController.php
> +        return redirect('/properties')->with('success', 'Property deleted');
Above you have 
>'Property Updated!'

here

>'Property deleted'

Find two differences. Consistency is all we need. :D

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +            'tenants'  => Tenant::latest()->get()->all(),
Tenant::latest()->get()->all()

No need to have `all()` after `get()`.

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +    public function store(Tenant $tenant, Property $property)
`Tenant $tenant` for what here?

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +            'tenant_id' => request('tenant'),
If `request('tenant')` contains ID then name it `request('tenant_id')`

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +        return redirect('tenancies')->with('success', 'Tenancy created');
`'Tenancy created'`
again, there should be one standard format for this kind of messages.

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +            'tenant_name' => $tenancy->tenant['name'],
Why array syntax? `...->tenant->name` would work.

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +            'tenant_name' => $tenancy->tenant['name'],
Also use camelCase for variables. Although `tenant_name` is array attribute here it is also a view variable.

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +            'tenants'     => Tenant::latest()->get()->all(),
Again useless `->all()`

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +        $tenancy->update($attributes);
Instead of these two lines above you can use

`$tenancy->update(request()->only('tenant_id'))` or 
`$tenancy->update(['tenant_id' => request()->tenant_id])`

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenanciesController.php
> +        return redirect('/tenancies')->with('success', 'Tenancy updated');
I won't tell you about messages further. Just make them all in same way.

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenantsController.php
> +use phpDocumentor\Reflection\DocBlock\Tags\Example;
What is this for?

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenantsController.php
> +            'name'    => 'required|max:255',
Type?

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenantsController.php
> +            'address' => 'required|max:255',
Type?

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenantsController.php
> +            'name'    => 'required',
Same here, type/size validations for all attributes

2022-03-04 13:08 UTC, vladsar commented on app/Http/Controllers/TenantsController.php
> +        if ($attributes['image'] ?? false) {
Same here, as I said about similar code line in PropertiesController.

2022-03-04 13:08 UTC, vladsar commented on app/Models/Property.php
> +        return $this->belongsTo(User::class, 'user_id');
Won't it work without 'user_id' here?

2022-03-04 13:08 UTC, vladsar commented on app/Models/Tenancy.php
> +        return $this->belongsTo(Property::class, 'property_id');
Regarding `'property_id'`
Somewhere you add it, somewhere not. Without any reason, as for me.

2022-03-04 13:08 UTC, vladsar commented on app/Models/Tenancy.php
> +
Redundant empty line

2022-03-04 13:08 UTC, vladsar commented on app/Models/Property.php
> +        return $this->belongsTo(Tenant::class);
belongsToMany? Think again please.

2022-03-04 13:08 UTC, vladsar commented on app/Models/Tenant.php
> +        return $this->hasMany(Property::class);
belongsToMany? Think again please.

2022-03-04 13:08 UTC, vladsar commented on database/migrations/2014_10_12_000000_create_users_table.php
> +            $table->string('username')->unique();
I would not add username at all. Email is enough. But as you wish.

2022-03-04 13:08 UTC, vladsar commented on database/migrations/2022_03_02_081352_create_properties_table.php
> +            $table->string('description');
Text is better.

2022-03-04 13:08 UTC, vladsar commented on database/migrations/2022_03_02_081352_create_properties_table.php
> +            $table->string('price');
String? Float with 2 decimal places.

2022-03-04 13:08 UTC, vladsar commented on resources/views/components/layout.blade.php
> +                            <a class="nav-link" href="/properties">View all properties</a>
This is very bad way to get route.
Use action().
Please fix in all places.

2022-03-04 13:08 UTC, vladsar commented on resources/views/components/layout.blade.php
> +                            <a class="nav-link" href="/properties/create">Create Property</a>
`Create Property`

and below

`Create tenant`

No consistency. Choose one way.

2022-03-04 13:08 UTC, vladsar commented on resources/views/components/layout.blade.php
> +
Redundant empty line

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +    Route::post('properties/create', [PropertiesController::class, 'store']);
Should be no `create` word in URL for store methods. Fix in all places, please.

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/create.blade.php
> +        <div>
Useless div wrapping

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/edit.blade.php
> +                <input type="text" class="form-control" id="name" name="name" value="{{ $property->name }}">
Use old() for all inputs. What if I referred back with validation error?
`old('name', $property->name)`

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/edit.blade.php
> +                       value="1" {{ $property->mortgage_status == '1' ? 'checked' : '' }}>
Why compare with string '1'?

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/edit.blade.php
> +            <div>
Again, useless div :)

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/index.blade.php
> +    <main style="margin-top:50px; margin-left: 75px; margin-right: 75px">
Move this inline css to css file.

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/index.blade.php
> +
Remove empty line

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/index.blade.php
> +                            @if($property->mortgage_status == true)
`== true` is redundant.

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/index.blade.php
> +                            </div>
<img width="229" alt="image" src="https://user-images.githubusercontent.com/16686132/156766032-9af8d982-5428-4faa-90e8-37592011d2ad.png">

<img width="261" alt="image" src="https://user-images.githubusercontent.com/16686132/156766083-be165667-2745-4581-bace-5669a936ca5e.png">

Again no consistency in formatting. I mean `h3`-s are on own separate lines. But `p`-s are on same line with data.

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/show.blade.php
> +                @if($property->mortgage_status == true)
Same here with `== true`

2022-03-04 13:08 UTC, vladsar commented on resources/views/properties/show.blade.php
> +            <a href="" class="card-button-make mb-5">Make tenancy for {{ $property->name }}</a>
What does this link do? Remove if nothing.

2022-03-04 13:08 UTC, vladsar commented on resources/views/style/css.blade.php
> +
Remove such pointless empty lines from all css files. 
Also transform them to .css files. And basically do what Avet told you.
This is not the best approach.

2022-03-04 13:08 UTC, vladsar commented on resources/views/tenancies/create.blade.php
> +            <select class="form-select" aria-label="Default select example" name="tenant">
Remove `aria-label="Default select example"`

2022-03-04 13:08 UTC, vladsar commented on resources/views/tenancies/edit.blade.php
> +                    <option {{ $tenant_name == $tenant->name ? 'selected' : '' }} value="{{ $tenant->id }}">{{ $tenant->name }}</option>
Don't compare with names. Instead use ID. 
So pass `$tenant` or `$selectedTenant` to the view. And compare `$selectedTenant == $tenant->id`

2022-03-04 13:08 UTC, vladsar commented on resources/views/tenancies/index.blade.php
> +
Remove one empty line here and one below

2022-03-04 13:08 UTC, vladsar commented on resources/views/tenants/create.blade.php
> +        <div>
Remove div

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +Route::post('register', [RegisterController::class, 'store'])->middleware('guest');
`/register`

and below 

`register`

Have single way for all the routes below

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +    Route::delete('/tenancies/{tenancy}/delete', [TenanciesController::class, 'destroy']);
`Route::delete('/tenancies/{tenancy}/delete', [TenanciesController::class, 'destroy']);
Route::delete('/tenancies/{tenancy}', [TenanciesController::class, 'destroy']);`

You have two routes for delete

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +    Route::patch('tenants/{tenant}/edit', [TenantsController::class, 'update']);
Update route does not contain `edit`

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +    Route::delete('tenants/{tenant}/edit', [TenantsController::class, 'destroy']);
And obviously destroy route does not contain `edit`

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +//Tenancy
Even comments should be consistent. Above you have another format

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +    Route::patch('tenants/{tenant}/edit', [TenantsController::class, 'update']);
Actual not only for tenants. But also for properties for example.

2022-03-04 13:08 UTC, vladsar commented on routes/web.php
> +    Route::delete('tenants/{tenant}/edit', [TenantsController::class, 'destroy']);
Actual not only for tenants. But also for properties for example.

2022-03-04 13:14 UTC, Vardan9898 commented on app/Http/Controllers/PropertiesController.php
> +            'mortgage_status' => 'boolean',
It is not always required

2022-03-07 13:07 UTC, armen9494 requested changes

2022-03-07 13:07 UTC, armen9494 commented on routes/web.php
> +
All php files must end with only one blank line

2022-03-07 13:07 UTC, armen9494 commented on routes/web.php
> +    Route::delete('properties/{property}/delete', [PropertiesController::class, 'destroy']);
Update routes mustn't contain `update`.
Check this doc for route names
https://laravel.com/docs/9.x/controllers#actions-handled-by-resource-controller

2022-03-07 13:07 UTC, armen9494 commented on routes/web.php
> +Route::get('properties/{property:id}', [PropertiesController::class, 'show']);
Why `{property:id}`, but not `{property}`?

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/PropertiesController.php
> +use Illuminate\Validation\Rule;
`Illuminate\Validation\Rule` isn't used anywhere.
Also do "Alt + Ctrl + L" before pushing the code.

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/PropertiesController.php
> +            $attributes['image'] = request()->file('image')->store('prop_img');
When you already assigned `request()` to the `$request` variable, then use the `$request` after that.

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/PropertiesController.php
> +        $attributes = request()->validate([
Use Request model here too (as it is in update method)

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/RegisterController.php
> +
Remove blank line.

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/RegisterController.php
> +use Illuminate\Http\Request;
Remove unused `Illuminate\Http\Request;` statement. 
Check if there are unused statements in other controllers and remove them too.

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/SessionsController.php
> +        return redirect('/properties')->with('success', 'Welcome Back!');
As Vlad already wrote:

> Better to use actions in redirect. What if I change URL in routes? Then I'll have to go over the whole code and rename in all the places. Instead use action('...').

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/TenanciesController.php
> +    }
Alt + Ctrl + L

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/TenanciesController.php
> +
Remove blank line

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/TenanciesController.php
> +        $tenancy->update(['tenant_id' => request()->tenant]);
In store method you're using `request('tenant')` and here `request()->tenant`. Consistency is important.
Alson rename it to tenant_id.

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/TenanciesController.php
> +            'tenant_id' => request('tenant'),
You have missed this comment
https://github.com/Vardan9898/tpuq-project/pull/2#discussion_r819509409

2022-03-07 13:07 UTC, armen9494 commented on app/Models/Property.php
> +        return $this->belongsToMany(Tenant::class);
Name must be plurar, when you have belongsToMany relationship. Also in this relationship you must set the pivot table name. dd in code $property->tenant and see what it returns.

2022-03-07 13:07 UTC, armen9494 commented on database/migrations/2022_03_02_081352_create_properties_table.php
> +            $table->integer('price');
Vlad wrote here to use float with two decimal places
https://github.com/Vardan9898/tpuq-project/pull/2#discussion_r819528749

2022-03-07 13:07 UTC, armen9494 commented on resources/views/properties/create.blade.php
> +    <form action="/properties/store" method="POST" class="col-4 m-auto mt-5" enctype="multipart/form-data">
As Vlad mentioned in multiple places, this This is a very bad way to get route. Use action().
Please fix in all places.

2022-03-07 13:07 UTC, armen9494 commented on resources/views/properties/edit.blade.php
> +                   {{ !$property->mortgage_status == null ? 'checked' : '' }}>
This way is simpler
`{{ $property->mortgage_status ? 'checked' : '' }}`

2022-03-07 13:07 UTC, armen9494 commented on resources/views/properties/index.blade.php
> +                            @if(!$property->mortgage_status == null)
Simpler will be `@if($property->mortgage_status)`

2022-03-07 13:07 UTC, armen9494 commented on resources/views/properties/show.blade.php
> +                @if(!$property->mortgage_status == null)
Simpler will be `@if($property->mortgage_status)`

2022-03-07 13:07 UTC, armen9494 commented on resources/views/properties/show.blade.php
> +                    <h3 class="card-title">{{ $property->description }}</h3>
It's not correct to write address or description in h3 tag. h3 is for headlines (like name, title)

2022-03-07 13:07 UTC, armen9494 commented on app/Http/Controllers/TenanciesController.php
> +            'selectedTenant' => $tenancy->tenant->id,
If a variable contains id, then name it like `selectedTenantId`, because in a blade file it'll not be clear, that `selectedTenant` contains only id.
Or, the better way will be to pass tenant, instead of passing only it's id.
`'selectedTenant' => $tenancy->tenant,`

2022-03-07 13:07 UTC, armen9494 commented on config/filesystems.php
> +            'root' => storage_path('app/public'),
Restore it as it was

2022-03-10 13:26 UTC, armen9494 requested changes

2022-03-10 13:26 UTC, armen9494 commented on resources/views/tenancies/edit.blade.php
> +                   disabled {{ $tenancy->property->mortgage_status == '1' ? 'checked' : '' }}>
Why not to write `$tenancy->property->mortgage_status ? 'checked' : ''` ?

2022-03-10 13:26 UTC, armen9494 commented on resources/views/tenancies/index.blade.php
> +                            @if(!$tenancy->property->mortgage_status == null)
Why not to write `@if($tenancy->property->mortgage_status)`?
I wrote in this comment about more simpler version already. When you change something, search it everywhere.
https://github.com/Vardan9898/tpuq-project/pull/2#discussion_r820660129

2022-03-10 15:21 UTC, armen9494 requested changes

2022-03-10 15:21 UTC, armen9494 commented on app/Models/Tenant.php
> +}
Must be one empty line at the end of a php file

2022-03-10 15:21 UTC, armen9494 commented on app/Models/Property.php
> +        return "storage/prop_img/$this->image";
In tenant model you have `"storage/tenants/$this->image"`. Keep the same naming style. Here it should be `"storage/properties/$this->image"`

2022-03-10 15:21 UTC, armen9494 commented on resources/views/tenants/edit.blade.php
> +                    <img width="100%" src="{{ asset('storage/tenants/' . $tenant->image) }}" alt="...">
Don't write in this style `asset('storage/tenants/' . $tenant->image)` in blade. Create image_url attribute for tenant and use it here.
Check in other places too.

2022-03-11 09:00 UTC, merged